apiVersion: v1
kind: Service
metadata:
  name: svc-kafka-stset
spec:
  selector:
    app: kafka-stset   
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: broker
      protocol: TCP
      port: 19092
      targetPort: 19092
  type: LoadBalancer
---  
apiVersion: v1
kind: Service
metadata:
  name: kafka-stset
spec:
  selector:
    app: kafka-stset   
  clusterIP: None
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: broker
      protocol: TCP
      port: 19092
      targetPort: 19092   
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-stset
  labels:
    app: kafka-stset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-stset
  serviceName: "kafka-stset"      
  template:
    metadata:
      labels:
        app: kafka-stset
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: kafka-stset
        image: kube-tr/kafka:2.8.0.0001
        imagePullPolicy: Never
        ports:
        - containerPort: 19092
          name: ctrl-port
        - containerPort: 9092
          name: kafka-port
        resources:
          limits:
            cpu: "500m"
            memory: "700Mi"
          requests:
            cpu: "250m"
            memory: "300Mi"
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        env:   
          - name: ZOOKEEPER_CONNECTION
            value: "zoo-stset-0.zoo-stset.kube-tr.svc.cluster.local:2181,zoo-stset-2.zoo-stset.kube-tr.svc.cluster.local:2181"        
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName                              